service: nodejs-web-crawler

frameworkVersion: ">=2.24.0"

package:
  patterns:
    - '!.build'

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  profile: ${env:AWS_PROFILE, 'default'}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  iam:
    role: ${env:AWS_IAM_ROLE, 'lambda'}
  apiGateway:
    shouldStartNameWithService: true

functions:
  crawler:
    handler: handler.webCrawler
    events:
      - http:
          path: /crawl
          method: get
